"""17_03_2021

Revision ID: 9affbd1138c4
Revises: e5809ade238c
Create Date: 2021-03-17 12:44:39.166844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9affbd1138c4'
down_revision = 'e5809ade238c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix__notice_msg__status'), 'notice_msg', ['status'], unique=False, postgresql_where=sa.text('status = 0'))
    op.alter_column('shop', 'sort',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'sort',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix__notice_msg__status'), table_name='notice_msg')
    # ### end Alembic commands ###
