"""16_03_2021

Revision ID: e5809ade238c
Revises: 71533b599a99
Create Date: 2021-03-16 16:40:31.396850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5809ade238c'
down_revision = '71533b599a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "btree_gin";')
    op.execute('CREATE INDEX "ix__product_stock__parameters" ON product_stock USING GIN (product_id, (parameters -> \'option_code\'), (parameters -> \'type_code\'));')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION "btree_gin";')
    op.execute('DROP INDEX "ix__product_stock__parameters";')
    # ### end Alembic commands ###
