"""04_02_2021

Revision ID: 535d1baa340d
Revises: 0708227a3e80
Create Date: 2021-02-04 14:55:15.499189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535d1baa340d'
down_revision = '0708227a3e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "btree_gin";')
    op.execute('CREATE INDEX "ix__product_stock__parameters" ON product_stock USING GIN (product_id, (parameters -> \'option_code\'), (parameters -> \'type_code\'));')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION "btree_gin";')
    op.execute('DROP INDEX "ix__product_stock__parameters";')
    # ### end Alembic commands ###
